admin_app/urls.py
from django.urls import path
from . import views

app_name = 'admin_app'
urlpatterns = [
    path('admin_index_view', views.admin_index_view, name='admin_index_view'),
    path('admin_dashboard_view', views.admin_dashboard_view, name='admin_dashboard_view'),
    path('admin_signup_view', views.admin_signup_view, name='admin_signup_view'),
    path('admin_login_view', views.admin_login_view, name='admin_login_view'),
    path('add_students_details_view', views.add_students_details_view, name='add_students_details_view'),
    path('update_students_details_email_view', views.update_students_details_email_view, name='update_students_details_email_view'),
    path('update_students_details_view', views.update_students_details_view, name='update_students_details_view'),
    path('log_details_view', views.log_details_view, name='log_details_view'),
    path('admin_settings_view', views.admin_settings_view, name='admin_settings_view'),
    path('deactivate_student_account_view', views.deactivate_student_account_view, name='deactivate_student_account_view'),

]

mockingbirds/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_app.urls')),
    path('', include('user_app.urls')),

]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'
urlpatterns = [
    path('', views.index_view, name='index_view'),
    path('success_msz_view', views.success_msz_view, name='success_msz_view'),

]

user_app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class query_model(models.Model):
    keywords = models.TextField(null=True)
    email=models.CharField(max_length=264,unique=False,blank=True,null=True)
    date_of_query=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.keywords)


class pdf_indexing_model(models.Model):
    pdf_title=models.TextField(unique=False,blank=True,null=True)
    pdf_abstract=models.TextField(unique=False,blank=True,null=True)
    pdf_path=models.TextField(unique=False,blank=True,null=True)
    pdf_creation_date=models.CharField(max_length=264,unique=False,blank=True,null=True)

    def __str__(self):
        return str(self.pdf_path)

class pdf_query_model(models.Model):
    email=models.ForeignKey(query_model, on_delete=models.CASCADE)
    pdf_path=models.ForeignKey(pdf_indexing_model, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.email)

user_app/forms.py
from django import forms

class SearchForm(forms.Form):
    keywords=forms.CharField(widget=forms.Textarea)
    email=forms.EmailField()

user_app/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from .forms import *
from .models import *
from admin_app.models import *
from sendemailsms import *
from backend.SearchEngine import *
import datetime
import threading


def index_view(request):
    form=SearchForm()
    freq_obj=and_or_search_model.objects.all()[:1]
    for f in freq_obj:
        frequency=f.frequency
        and_or=f.and_or_search
    if request.method == 'POST':
        Engine=SearchEngine('IndexedDatabase')
        SimilarEngine = SimilaritySearchEngine()

        form=SearchForm(request.POST)
        print("printing result")
        pdf_path_list=[]
        similar_paths = []

        print(form.is_valid())
        if form.is_valid():
            keywords = form.cleaned_data.get('keywords')
            email = form.cleaned_data.get('email')
            reg_no=form.cleaned_data.get('reg_no')
            new_query=query_model.objects.create(keywords=keywords, email=email)
            print("keywords",keywords)
            result_list_accurate=Engine.search(keywords, pdf_path_list, operation=and_or.upper())
            result_list_similar=SimilarEngine.search(keywords, pdf_path_list, operation=and_or.upper())

            for pz in result_list_similar:
                similar_paths.append(pz['pdf_path'])


            print("result_list:",result_list_accurate)
            # for pz in result_list:
            #     print(pz['title'],pz['abstract'],pz['pdf_path'],pz['creation_date'])
            for pz in result_list_accurate:
                set_pdf=pdf_indexing_model.objects.create(pdf_title=pz['title'],pdf_abstract=pz['abstract'],pdf_path=pz['pdf_path'],pdf_creation_date=pz['creation_date'])
                assign_pdf=pdf_query_model.objects.create(email=new_query,pdf_path=set_pdf)
                pdf_path_list.append(pz['pdf_path'])
            emailsms=SendEmailSms(fromaddr='pdhindujaa@gmail.com', from_password='!1q2w3e4r5t%', toaddr=[email])
            emailsms.send(pdf_path_list)
            emailsms.send(similar_paths)


            return redirect('user_app:success_msz_view')
        else:
            return render(request,'user_app/user.html',{'form':form})
    return render(request,'user_app/user.html',{'form':form})



def success_msz_view(request):
    return render(request,'user_app/success_msz.html',{})

templates/user_app/success_msz.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>user</title>
    <!-- bootstrap-css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/success_msz.css' %}">

  </head>
  <body >
    <div class="msz justify-content-center text-center">

Your query is submitted successfully and related document will be sent to your email

    </div>

    <!-- Bootstrap-js -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>


  </body>
</html>

templates/user_app/user.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>user</title>
    <!-- bootstrap-css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/user.css' %}">

  </head>
  <body >
    <a href="{% url 'admin_app:admin_index_view' %}" class="btn_1 btn_admin">Admin</a>
    <div class="head-title">Search Keywords</div>


    <div class="row justify-content-center center-div">


      <form action="{% url 'user_app:index_view' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="row row-div-1">
            <label>
              <span class="label key_label">Keywords</span>
              {{ form.keywords.errors }}
              {{ form.keywords}}
            </label>
            </div>
            <div class="row row-div-2">
            <div class="col-5">
              <span class="label">Email</span>
                {{ form.email.errors }}
                {{ form.email}}
            </div>
            </div><br>
            <!-- Trigger/Open The Modal -->
            <input type="Submit" id="myBtn" class="btn_1" value="Submit">
          </form>
          <!-- The Modal -->
             <div id="myModal" class="modal">

            <!-- Modal content -->
            <div class="modal-content">
              <span class="close">&times;</span>
              <p>Your query is submitted successfully and related document will be sent to your email</p>
            </div>

            </div>


    </div>




    <!-- jscript -->
    <script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
  modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>

    <!-- Bootstrap-js -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>


  </body>
</html>