admin_app/urls.py
from django.urls import path
from . import views

app_name = 'admin_app'
urlpatterns = [
    path('admin_index_view', views.admin_index_view, name='admin_index_view'),
    path('admin_dashboard_view', views.admin_dashboard_view, name='admin_dashboard_view'),
    path('admin_signup_view', views.admin_signup_view, name='admin_signup_view'),
    path('admin_login_view', views.admin_login_view, name='admin_login_view'),
    path('add_students_details_view', views.add_students_details_view, name='add_students_details_view'),
    path('update_students_details_email_view', views.update_students_details_email_view, name='update_students_details_email_view'),
    path('update_students_details_view', views.update_students_details_view, name='update_students_details_view'),
    path('log_details_view', views.log_details_view, name='log_details_view'),
    path('admin_settings_view', views.admin_settings_view, name='admin_settings_view'),
    path('deactivate_student_account_view', views.deactivate_student_account_view, name='deactivate_student_account_view'),

]

mockingbirds/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_app.urls')),
    path('', include('user_app.urls')),

]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'
urlpatterns = [
    path('', views.index_view, name='index_view'),
    path('success_msz_view', views.success_msz_view, name='success_msz_view'),

]

admin_app/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class student_model(models.Model):
    name = models.CharField(max_length=264,unique=False,blank=True,null=True)
    email=models.EmailField(blank=True, null=True, unique=True)
    research_department_email=models.EmailField()
    research_department_name=models.CharField(max_length=264,unique=False,blank=True,null=True)
    research_department_phone=models.IntegerField(default=91)
    faculty_incharge_email=models.EmailField()
    faculty_incharge_name=models.CharField(max_length=264,unique=False,blank=True,null=True)
    faculty_incharge_phone=models.IntegerField(default=91)
    phone_no=models.IntegerField(default=91)
    research_area=models.CharField(max_length=264,unique=False,blank=True,null=True)
    date_of_tenure_completion=models.DateField(blank=True,null=True)
    keywords = models.TextField(null=True)
    date_of_query=models.DateField(default=datetime.now,blank=True,null=True)

    def __str__(self):
        return str(self.email)
class student_status_model(models.Model):
    email=models.ForeignKey(student_model, on_delete=models.CASCADE)
    status=models.IntegerField(default=1)
    date_of_query=models.DateField(default=datetime.now,blank=True,null=True)

    def __str__(self):
        return str(self.email)

class and_or_search_model(models.Model):
    SEARCH_CHOICES=(('and','and'),('or','or'))
    and_or_search=models.CharField(max_length=5, choices=SEARCH_CHOICES, default='and')
    frequency=models.IntegerField(default=1)
    email=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    date_of_query=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.email)

class pdf_indexing_model2(models.Model):
    pdf_title=models.TextField(unique=False,blank=True,null=True)
    pdf_abstract=models.TextField(unique=False,blank=True,null=True)
    pdf_path=models.TextField(unique=True,blank=True,null=True)
    pdf_creation_date=models.CharField(max_length=264,unique=False,blank=True,null=True)

    def __str__(self):
        return str(self.pdf_path)

class pdf_query_model2(models.Model):
    email=models.ForeignKey(student_model, on_delete=models.CASCADE)
    pdf_path=models.ForeignKey(pdf_indexing_model2, on_delete=models.CASCADE)
    date_of_query=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.email)


class log_data_model(models.Model):
    date_of_query=models.DateTimeField(default=timezone.now)
    log=models.CharField(max_length=264,unique=False,blank=True,null=True)
    short_log=models.CharField(max_length=264,unique=False,blank=True,null=True)

    def __str__(self):
        return str(self.date_of_query)

admin_app/forms.py
from django import forms
import datetime
from django.db import models
from .models import *
from django.contrib.admin import widgets
from django.forms.fields import DateField


class DateInput(forms.DateInput):
    input_type = 'date'

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

class SignupForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

class StudentDetailsForm(forms.ModelForm):

    class Meta:
        model = student_model
        fields = ['name','email', 'research_department_email','faculty_incharge_email','faculty_incharge_name','faculty_incharge_phone','phone_no','research_area','date_of_tenure_completion','keywords','research_department_name','research_department_phone']
        exclude=['date_of_query',]
        widgets = {
                    'date_of_tenure_completion': DateInput(),
                }
class StudentUpdateEmail(forms.Form):
    email = forms.EmailField()

class and_or_search(forms.ModelForm):

    class Meta:
        model = and_or_search_model
        fields=['and_or_search','frequency']
        exclude=['email','date_of_query']

admin_app/views.py
from __future__ import absolute_import, unicode_literals
from celery import task

from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from .forms import *
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import (authenticate,
                                 login,
                                 logout
                                 )
from django.contrib.auth.decorators import login_required
from sendemailsms import *
from backend.SearchEngine import *
from IndexDatabase import Indexer
from django.utils import timezone
from datetime import datetime


#log_query=log_data_model.objects.create(log=log,short_log=short_log)

def admin_index_view(request):
    form1=LoginForm()
    form2=SignupForm()
    return render(request,'admin_app/admin_index.html',{'form1':form1,'form2':form2})

def admin_signup_view(request):
    if request.method == 'POST':
        form1=LoginForm(request.POST)
        form2=SignupForm(request.POST)
        if form2.is_valid():
            name = form2.cleaned_data.get('name')
            email = form2.cleaned_data.get('email')
            user_obj=User.objects.filter(email=email)
            if user_obj == None:
                raw_password = form2.cleaned_data.get('password')
                user_new = User.objects.create_user(email,email,raw_password)
                user_new.first_name = name
                user_new.save()
                user = authenticate(username=email, password=raw_password)
                login(request, user)
                log="admin signed up for the first time"
                short_log="adminsignup"
                log_query=log_data_model.objects.create(log=log,short_log=short_log)
                return redirect('admin_app:admin_dashboard_view')
            else:
                return redirect('admin_app:admin_index_view')

    return render(request,'admin_app/admin_index.html',{})

def admin_login_view(request):
    print("admin_login_view")
    error_msz=0
    if request.method == 'POST':
        print("nik")
        password = request.POST.get('password')
        email = request.POST.get('email')
        user = authenticate(username=email, password=password)
        if(user==None):
            error_msz=1
            return redirect('admin_app:admin_index_view')

        print(user)
        if user:
            if user.is_active:
                login(request,user)
                log="admin logged in "
                short_log="adminlogin"
                log_query=log_data_model.objects.create(log=log,short_log=short_log)
                return redirect('admin_app:admin_dashboard_view')
            else:
                return render(request,'admin_app/admin_index.html',{})
        else:
            error_msz=1
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return redirect('admin_app:admin_index_view')
    return render(request,'admin_app/add_students_details_view.html',{'error_msz':error_msz})

def admin_dashboard_view(request):
    return render(request,'admin_app/admin_dashboard.html',{})

def add_students_details_view(request):
    success=0
    error_msz2=0
    form=StudentDetailsForm()
    freq_obj=and_or_search_model.objects.all()[:1]
    print(freq_obj)
    for f in freq_obj:
        frequency=f.frequency
        and_or=f.and_or_search
        print(frequency,and_or)
    if request.method == 'POST':
        Engine=SearchEngine('IndexedDatabase')
        SimilarEngine = SimilaritySearchEngine()
        form=StudentDetailsForm(request.POST)
        print("nikbackput",form.is_valid())
        pdf_path_list=[]
        if form.is_valid():
            new_query=form.save(commit = False)
            new_query.save()
            keywords = form.cleaned_data.get('keywords')
            email = form.cleaned_data.get('email')
            name = form.cleaned_data.get('name')
            int_one=int(1)
            print(type(int_one))
            new_student=student_status_model.objects.create(email=new_query,status=int_one)

            log="  new account created for {}".format(name)
            short_log="new_acc_created"
            log_query=log_data_model.objects.create(log=log,short_log=short_log)

            success=1
            old_pdf_list=[]
            similar_paths = []
            print("keywords",keywords)
            result_list_accurate=Engine.search(keywords, old_pdf_list, operation=and_or.upper())

            result_list_similar=SimilarEngine.search(keywords, old_pdf_list, operation=and_or.upper())

            for pz in result_list_similar:
                similar_paths.append(pz['pdf_path'])

            print("result_list:",result_list_accurate)
            # for pz in result_list:
            #     print(pz['title'],pz['abstract'],pz['pdf_path'],pz['creation_date'])
            for pz in result_list_accurate:
                set_pdf=pdf_indexing_model2.objects.create(pdf_title=pz['title'],pdf_abstract=pz['abstract'],pdf_path=pz['pdf_path'],pdf_creation_date=pz['creation_date'])
                assign_pdf=pdf_query_model2.objects.create(email=new_query,pdf_path=set_pdf)
                pdf_path_list.append(pz['pdf_path'])
            log="email sent to {} name={} with pdfs {} for keywords {}".format(email,name,pdf_path_list,keywords)
            short_log="email_pdf"
            log_query=log_data_model.objects.create(log=log,short_log=short_log)

            emailsms=SendEmailSms(fromaddr='pdhindujaa@gmail.com', from_password='!1q2w3e4r5t%', toaddr=[email])
            body = ''
            for res in result_list_accurate:
                body += '{} with {} relevance\n'.format(res['title'], res['relevance'])

            emailsms.send(pdf_path_list)

            emailsms.send(similar_paths)

            return render(request,'admin_app/twobuttons.html',{'form':form,'success':success})
        else:
            error_msz2=1
            return render(request,'admin_app/add_students_details.html',{'form':form,'success':success,'error_msz2':error_msz2})
    return render(request,'admin_app/add_students_details.html',{'form':form,'success':success,'error_msz2':error_msz2})

def update_students_details_email_view(request):
    error_msz3=0
    form=StudentUpdateEmail()
    if request.method == 'POST':
        form=StudentUpdateEmail(request.POST)
        print("nikbackput",form.is_valid())
        if form.is_valid():
            email=request.POST.get('email')
            request.session['email'] = email
            return redirect('admin_app:update_students_details_view')
        else:
            error_msz3=1
    else:
        error_msz3=1
    return render(request,'admin_app/update_students_details_email.html',{'form':form,'error_msz3':error_msz3})

def update_students_details_view(request):
    error_msz4=0
    success=0
    old_keywords=None
    freq_obj=and_or_search_model.objects.all()[:1]
    for f in freq_obj:
        frequency=f.frequency
        and_or=f.and_or_search

    email=request.session.get('email')
    print("session email",email)
    if request.method == 'GET':
        old_keywords=None
        try:
            print("nik1")
            form=StudentDetailsForm(request.GET or None,instance=student_model.objects.get(email=email))
            student_obj=student_model.objects.filter(email=email)
            for x in student_obj:
                old_keywords=x.keywords
            print("nik2",form)
        except:
            print("nik3")
            form=StudentDetailsForm(request.GET or None)
            print("nik3")

    elif request.method == 'POST':
        print("jatin in post")
        Engine=SearchEngine('IndexedDatabase')
        SimilarEngine = SimilaritySearchEngine()

        try:
            form=StudentDetailsForm(request.POST or None,instance=student_model.objects.get(email=email))
            print("form",form)
            student_obj=student_model.objects.filter(email=email)
            for x in student_obj:
                old_keywords=x.keywords
        except:
            form=StudentDetailsForm(request.POST or None)
        pdf_path_list=[]
        print("is valid",form.is_valid())
        if form.is_valid():
            print("jatin log=========",email)
            log="  student details updated for {}".format(email)
            short_log="updated_info"
            log_query=log_data_model.objects.create(log=log,short_log=short_log)
            new_keywords = form.cleaned_data.get('keywords')
            student_details_obj = form.save(commit=False)
            student_details_obj.email = email
            student_details_obj.save()
            success=1
            similar_paths = []

            if old_keywords==None:
                print("keywords",new_keywords)
                result_list_accurate=Engine.search(new_keywords, pdf_path_list, operation=and_or.upper())
                result_list_similar=SimilarEngine.search(keywords, old_pdf_list, operation=and_or.upper())

                print("result_list:",result_list_accurate)
                # for pz in result_list:
                #     print(pz['title'],pz['abstract'],pz['pdf_path'],pz['creation_date'])
                for pz in result_list_accurate:
                    set_pdf=pdf_indexing_model2.objects.create(pdf_title=pz['title'],pdf_abstract=pz['abstract'],pdf_path=pz['pdf_path'],pdf_creation_date=pz['creation_date'])
                    assign_pdf=pdf_query_model2.objects.create(email=student_details_obj,pdf_path=set_pdf)
                    pdf_path_list.append(pz['pdf_path'])

                for pz in result_list_similar:
                    similar_paths.append(pz['pdf_path'])


                emailsms=SendEmailSms(fromaddr='pdhindujaa@gmail.com', from_password='!1q2w3e4r5t%', toaddr=[email])
                emailsms.send(pdf_path_list)

                emailsms.send(similar_paths)

templates/admin_app/add_students_details.html
<!DOCTYPE html>
{% load static %}
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Add student details</title>


  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
  <link rel="stylesheet" href="{%static 'css/add_students_details.css' %}">

</head>
<body>
  <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6   col-div text-center">
    <a href="{% url 'admin_app:admin_dashboard_view' %}" class="btn1 btn_admin">Admin Dashboard</a>
  </div>

  <div class="form  text-center align-content-center">
    <h2>Add Student Details</h2>
    {% if success %}
      <p style="color: green;font-size:30px;padding:20px;border-style: dashed;border-color: green;border-width: 2px;background-color:#adc6a5;">
          Student details saved successfully add another !
      </p>
    {% endif %}

    <form action="{% url 'admin_app:add_students_details_view' %}" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="small-div">
        <span>Name</span>
        {{ form.name.errors }}
        {{ form.name}}
      </div>
      <div class="small-div">
        <span>Email</span>
        {{ form.email.errors }}
        {{ form.email}}
      </div>
      <div class="small-div">
        <span>Phone no.</span>
        {{ form.phone_no.errors }}
        {{ form.phone_no}}
      </div>
      <div class="small-div">
        <span>Guide name</span>
        {{ form.research_department_name.errors }}
        {{ form.research_department_name}}
      </div>
      <div class="small-div">
        <span>Guide email</span>
        {{ form.research_department_email.errors }}
        {{ form.research_department_email}}
      </div>
      <div class="small-div">
        <span>Guide Phone</span>
        {{ form.research_department_phone.errors }}
        {{ form.research_department_phone}}
      </div>
      <div class="small-div">
        <span>Faculty incharge name</span>
        {{ form.faculty_incharge_name.errors }}
        {{ form.faculty_incharge_name}}
      </div>
      <div class="small-div">
        <span>Faculty incharge email</span>
        {{ form.faculty_incharge_email.errors }}
        {{ form.faculty_incharge_email}}
      </div>
      <div class="small-div">
        <span>Faculty incharge Phone no.</span>
        {{ form.faculty_incharge_phone.errors }}
        {{ form.faculty_incharge_phone}}
      </div>

      <div class="small-div">
        <span>Research area</span>
        {{ form.research_area.errors }}
        {{ form.research_area}}
      </div>

      <div class="small-div">
        <span>Date of tenure completion</span>
        {{ form.date_of_tenure_completion.errors }}
        {{ form.date_of_tenure_completion}}
      </div>
      <div class="small-div">
        <span>keywords</span>
        {{ form.keywords.errors }}
        {{ form.keywords}}
      </div>

      <!-- Trigger/Open The Modal -->
      <input type="Submit" id="myBtn" class="btn1 btn_add" value="Add Student">
    </form>
    <!-- The Modal -->
       <div id="myModal" class="modal">

      <!-- Modal content -->
      <div class="modal-content">
        <span class="close">&times;</span>
        <p>Your query is submitted successfully and related document will be sent to the students email.</p>
      </div>

      </div>







</div>

<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
if (event.target == modal) {
modal.style.display = "none";
}
}
</script>
<script  src="{%static 'js/index.js' %}"></script>

</body>
</html>

templates/admin_app/admin_dashboard.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Admin</title>
    <!-- bootstrap-css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/admin_dashboard.css' %}">

  </head>
  <body >
    <div class="head-title">Admin</div>


    <div class="row justify-content-center center-div">
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6   col-div text-center">
        <a href="{% url 'admin_app:add_students_details_view' %}" class="btn1 ">Add Students details</a>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6  col-div text-center">
        <a href="{% url 'admin_app:update_students_details_email_view' %}" class="btn1 ">Update Students Details</a>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6  col-div text-center">
        <a href="{% url 'admin_app:log_details_view' %}" class="btn1 ">Activity Log</a>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6  col-div text-center">
        <a href="{% url 'admin_app:admin_settings_view' %}" class="btn1 ">Settings</a>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6  col-div text-center">
        <a href="{% url 'admin_app:deactivate_student_account_view' %}" class="btn1 ">Deactivate any user</a>
      </div>
    </div>






    <!-- Bootstrap-js -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>


  </body>
</html>

templates/admin_app/admin_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Admin Login/Registration</title>


  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
  <link rel="stylesheet" href="{%static 'css/style.css' %}">

</head>
<body>
<div class="cont">
  <div class="form sign-in">
    <h2>Welcome back</h2>

    <form action="{% url 'admin_app:admin_login_view' %}" method="post">
      {% csrf_token %}
      {{ form1.non_field_errors }}
      <label>
        <span>Email</span>
        {{ form1.email.errors }}
        {{ form1.email}}
      </label>
      <label>
        <span>Password</span>
          {{ form1.password.errors }}
          {{ form1.password}}
      </label>
      <p class="forgot-pass">Forgot password?</p>
      <input type="submit" class="submit" value="SignIn">
    </form>


  </div>
  <div class="sub-cont">
    <div class="img">
      <div class="img__text m--up">
        <h2>New here?</h2>
        <p>Sign up and discover great amount of new opportunities!</p>
      </div>
      <div class="img__text m--in">
        <h2>Already a member?</h2>
        <p>If you already has an account, just sign in.</p>
      </div>
      <div class="img__btn">
        <span class="m--up">Sign Up</span>
        <span class="m--in">Sign In</span>
      </div>
    </div>
    <div class="form sign-up">
      <h2>Create an Account</h2>


      <form action="{% url 'admin_app:admin_signup_view' %}" method="post">
        {% csrf_token %}
        {{ form2.non_field_errors }}
            <label>
              <span>Name</span>
              {{ form2.name.errors }}
              {{ form2.name}}
            </label>
            <label>
              <span>Email</span>
              {{ form2.email.errors }}
              {{ form2.email}}
            </label>
            <label>
              <span>Password</span>
              {{ form2.password.errors }}
              {{ form2.password}}
            </label>
            <input type="submit" class="submit" value="Sign Up">
      </form>
    </div>
  </div>
</div>


<script  src="{%static 'js/index.js' %}"></script>

</body>
</html>

templates/admin_app/admin_settings.html
<!DOCTYPE html>
{% load static %}
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Settings</title>


  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
  <link rel="stylesheet" href="{%static 'css/admin_settings.css' %}">
  </head>
  <body>
    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6   col-div text-center">
      <a href="{% url 'admin_app:admin_dashboard_view' %}" class="btn1 btn_admin">Admin Dashboard</a>
    </div>
<div class="form">
    <form action="{% url 'admin_app:admin_settings_view' %}" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}

      <div class="small-div ">
        <span>and_or_search</span>
        {{ form.and_or_search.errors }}
        {{ form.and_or_search}}
      </div>
      <div class="small-div ">frequency
        <span>frequency</span>
        {{ form.frequency.errors }}
        {{ form.frequency}}
      </div>


      <input type="submit" class="submit btn1 btn_add" value="Update Settings">
    </form>

  </div>
  </body>
</html>

templates/admin_app/deactivate_student_account.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Add student details</title>


    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel="stylesheet" href="{%static 'css/update_students_details_email.css' %}">
  </head>
  <body>

    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6   col-div text-center">
      <a href="{% url 'admin_app:admin_dashboard_view' %}" class="btn1 btn_admin">Admin Dashboard</a>
    </div>
    <form action="{% url 'admin_app:update_students_details_email_view' %}" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}

      <div class="form">
        <span>Email</span>
        {{ form.email.errors }}
        {{ form.email}}
      </div>


      <input type="submit" class="submit btn1 btn_add" value="Deactivate Student">
    </form>


  </body>
</html>

templates/admin_app/twobuttons.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>buttons</title>
    <!-- bootstrap-css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/admin_dashboard.css' %}">

  </head>
  <body >
    <div class="head-title">Go to .....</div>

    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6   col-div text-center">
      <a href="{% url 'admin_app:admin_dashboard_view' %}" class="btn1 ">Admin Dashboard</a>
    </div>
    <div class="row justify-content-center center-div">
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6   col-div text-center">
        <a href="{% url 'admin_app:add_students_details_view' %}" class="btn1 ">Add another Students details</a>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6  col-div text-center">
        <a href="{% url 'admin_app:update_students_details_email_view' %}" class="btn1 ">Update Students Details</a>
      </div>
    </div>






    <!-- Bootstrap-js -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>


  </body>
</html>